"""initial

Revision ID: c364d271c054
Revises: 
Create Date: 2026-08-12 20:16:24.497623
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c364d271c054'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_full_name'), 'guests', ['full_name'], unique=False)
    op.create_index(op.f('ix_guests_organization_id'), 'guests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('hotel', 'apartment_building', 'mixed', name='propertytype', native_enum=False, length=40), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name_or_number', sa.String(length=100), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cleaning_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'out_of_service', name='unitstatus', native_enum=False, length=40), nullable=False),
    sa.Column('housekeeping_status', sa.Enum('dirty', 'cleaning', 'clean', 'maintenance', name='housekeepingstatus', native_enum=False, length=40), nullable=False),
    sa.Column('floor', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'name_or_number', name='uq_unit_name_per_property')
    )
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('airbnb', 'booking', 'phone', 'whatsapp', 'email', name='reservationsource', native_enum=False, length=40), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'in_house', 'checked_out', 'canceled', 'no_show', name='reservationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fees_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('airbnb_payout', 'booking_payout', 'cash', 'bank_transfer', 'card', name='paymentmethod', native_enum=False, length=40), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'partially_paid', 'refunded', name='paymentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_date > check_in_date', name='ck_reservation_date_order'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_check_in_date'), 'reservations', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_reservations_check_out_date'), 'reservations', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_guest_id'), 'reservations', ['guest_id'], unique=False)
    op.create_index('ix_reservations_property_dates', 'reservations', ['property_id', 'check_in_date', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_property_id'), 'reservations', ['property_id'], unique=False)
    op.create_index(op.f('ix_reservations_source'), 'reservations', ['source'], unique=False)
    op.create_index(op.f('ix_reservations_source_reference'), 'reservations', ['source_reference'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index('ix_reservations_unit_dates', 'reservations', ['unit_id', 'check_in_date', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_unit_id'), 'reservations', ['unit_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('airbnb', 'booking', 'cash', 'bank_transfer', name='payoutsource', native_enum=False, length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_payout_date'), 'payouts', ['payout_date'], unique=False)
    op.create_index(op.f('ix_payouts_reservation_id'), 'payouts', ['reservation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('housekeeping_checkout_clean', 'housekeeping_stayover_clean', 'maintenance_issue', 'inspection', 'other', name='tasktype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'canceled', name='taskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskpriority', native_enum=False, length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes_room_status_to', sa.Enum('dirty', 'cleaning', 'clean', 'maintenance', name='housekeepingstatus', native_enum=False, length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_property_due', 'tasks', ['property_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_property_id'), 'tasks', ['property_id'], unique=False)
    op.create_index(op.f('ix_tasks_reservation_id'), 'tasks', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_unit_due', 'tasks', ['unit_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_unit_id'), 'tasks', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_unit_id'), table_name='tasks')
    op.drop_index('ix_tasks_unit_due', table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_reservation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_property_id'), table_name='tasks')
    op.drop_index('ix_tasks_property_due', table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_payouts_reservation_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_payout_date'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_reservations_unit_id'), table_name='reservations')
    op.drop_index('ix_reservations_unit_dates', table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_source_reference'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_source'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_property_id'), table_name='reservations')
    op.drop_index('ix_reservations_property_dates', table_name='reservations')
    op.drop_index(op.f('ix_reservations_guest_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_out_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_in_date'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_organization_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_full_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_table('guests')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
